name: smart_kisan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.5
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
    - assets/sk.jpg
    - assets/Onboarding1.png
    - assets/Onboarding2.png
    - assets/Onboarding3.png
    - assets/Ls.png
    - assets/Fb.png
    - assets/Google.png
    - assets/Fp.png

# Fonts Section
  # fonts:
  #   - family: Arimo
  #     fonts:
  #       - asset: assets/fonts/Arimo-Regular.ttf
  #       - asset: assets/fonts/Arimo-Bold.ttf
  #         weight: 700
  #   - family: PT Sans
  #     fonts:
  #       - asset: assets/fonts/PTSans-Regular.ttf
  #       - asset: assets/fonts/PTSans-Bold.ttf
  #         weight: 700